// Downloads the woff2 subsets the site actually uses from Google Fonts and
// writes public/fonts/ plus src/fonts.css.
//
// Not part of `npm run build` — the outputs are committed, so builds and CI need
// no network. Re-run with `node scripts/fonts.mjs` when the type stack changes.

import { mkdir, writeFile, readdir, unlink } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const outDir = join(root, 'public', 'fonts')

// A modern UA gets woff2; older ones get ttf/eot.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

// Only the subsets we serve. latin-ext/cyrillic-ext/greek/vietnamese are dropped:
// the site is Russian and English.
const KEEP_SUBSETS = new Set(['latin', 'cyrillic'])

const FAMILIES = [
  // Inter is --sans: body copy plus every heading weight in App.css.
  { family: 'Inter', weights: [400, 500, 600, 700, 800] },
  // JetBrains Mono is --mono: code blocks and inline code.
  { family: 'JetBrains Mono', weights: [400, 500, 600] },
  // Unbounded is used for exactly one element, the VerificaHub wordmark.
  { family: 'Unbounded', weights: [800] },
]

/**
 * Google serves one @font-face per subset, each with its own unicode-range and
 * a comment naming the subset. Parse those triples out of the stylesheet.
 */
function parseFaces(css) {
  const faces = []
  const re =
    /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g
  let m
  while ((m = re.exec(css))) {
    const subset = m[1]
    const body = m[2]
    const url = body.match(/url\((https:\/\/[^)]+)\)/)?.[1]
    const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim()
    const weight = body.match(/font-weight:\s*(\d+)/)?.[1]
    if (url && range && weight) faces.push({ subset, url, range, weight: Number(weight) })
  }
  return faces
}

const slug = (family) => family.toLowerCase().replace(/\s+/g, '-')

await mkdir(outDir, { recursive: true })
for (const stale of await readdir(outDir).catch(() => [])) {
  await unlink(join(outDir, stale))
}

const rules = []
let total = 0

for (const { family, weights } of FAMILIES) {
  const query = `${family.replace(/ /g, '+')}:wght@${weights.join(';')}`
  const css = await fetch(`https://fonts.googleapis.com/css2?family=${query}&display=swap`, {
    headers: { 'User-Agent': UA },
  }).then((r) => r.text())

  // All three families ship as variable fonts: Google emits one @font-face per
  // requested weight, but every one points at the same file. Collapse them into
  // a single face per subset carrying the whole weight range.
  const bySubset = new Map()
  for (const face of parseFaces(css)) {
    if (!KEEP_SUBSETS.has(face.subset)) continue
    const existing = bySubset.get(face.subset)
    if (existing) {
      if (existing.url !== face.url) {
        throw new Error(`${family}/${face.subset}: expected one variable file, got several URLs`)
      }
      existing.min = Math.min(existing.min, face.weight)
      existing.max = Math.max(existing.max, face.weight)
    } else {
      bySubset.set(face.subset, { ...face, min: face.weight, max: face.weight })
    }
  }

  for (const [subset, face] of bySubset) {
    const name = `${slug(family)}-${subset}.woff2`
    const bytes = Buffer.from(await fetch(face.url).then((r) => r.arrayBuffer()))
    await writeFile(join(outDir, name), bytes)
    total += bytes.length

    const weight = face.min === face.max ? `${face.min}` : `${face.min} ${face.max}`
    rules.push(
      [
        '@font-face {',
        `  font-family: '${family}';`,
        '  font-style: normal;',
        `  font-weight: ${weight};`,
        '  font-display: swap;',
        `  src: url('/fonts/${name}') format('woff2');`,
        `  unicode-range: ${face.range};`,
        '}',
      ].join('\n'),
    )
    console.log(`${name.padEnd(32)} w:${weight.padEnd(8)} ${(bytes.length / 1024).toFixed(1).padStart(6)} KB`)
  }
}

const header = [
  '/*',
  ' * Self-hosted fonts. Generated by scripts/fonts.mjs — do not edit by hand.',
  ' *',
  ' * Self-hosting removes a render-blocking cross-origin stylesheet from the',
  ' * critical path, and keeps visitor IPs away from Google (the EU GDPR issue',
  ' * with the Google Fonts CDN). unicode-range means a page only fetches the',
  ' * subsets it actually paints.',
  ' */',
  '',
].join('\n')

await writeFile(join(root, 'src', 'fonts.css'), `${header}${rules.join('\n\n')}\n`, 'utf8')
console.log(`\n${rules.length} faces, ${(total / 1024).toFixed(0)} KB total -> public/fonts + src/fonts.css`)
